const actionTypes = {
  NEW_MOVE: "NEW_MOVE",
  GENRATE_CANDIDATE_MOVE: "GENRATE_CANDIDATE_MOVE",
  CLEAR_CANDIDATE_MOVE: "CLEAR_CANDIDATE_MOVE",
  OPEN_PROMOTION: "OPEN_PROMOTION",
};

export default actionTypes;
