const actionTypes = {
  NEW_MOVE: "NEW_MOVE",
  GENRATE_CANDIDATE_MOVE: "GENRATE_CANDIDATE_MOVE",
  CLEAR_CANDIDATE_MOVE: "CLEAR_CANDIDATE_MOVE",
  PROMOTION_OPEN: "PROMOTION_OPEN",
  PROMOTION_CLOSE: "PROMOTION_CLOSE",
};

export default actionTypes;
